luku = int(input("Anna kokonaisluku "))
luku2 = int(input("Anna toinen kokonaisluku "))
luku3 = int(input("Anna kolmas kokonaisluku "))
print("Lukujen summa: " + str(luku+luku2+luku3))
print("Lukujen tulo: " + str(luku*luku2*luku3))
print("Lukujen keskiarvo:  " + str(luku/3+luku2/3+luku3/3))